[package]
name = "nadir-notify"
version = "0.1.0"
authors = ["Rynco Maekawa <lynzrand@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nadir-types = { path = "crates/nadir-types" }
cursive = { version = "0.16", default-features = false, features = ["crossterm-backend"] }
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
crossbeam = "0.8"
arcstr = "1"
clru = "0.4"
parking_lot = "0.11"
smol_str = { version = "0.1", features = ["serde"] }

unicode-segmentation = "1"
unicode-width = "0.1"
unicode-truncate = "0.2"

thiserror = "1"

[workspace]
members = [".", "crates/*"]
